### ISSUE TITLE
As a normal user, I want to be able to post an answer under a question, so that I can solve the problem of others. Sub-story of #19

### ISSUE THREAD

**Issue by ChenChenYellow** [DrakeHunterK7/SOEN-341-Fall-2021-Team-9-Stack-Bubbling-#10]
As an User of the website, I want to be able to post an answer under a question, so that I can solve the problem of others.
Related to epic story #19

Story Points: 5

**Comment by DrakeHunterK7** [comment]
Tasks needed to be done to complete this User Story:

- [ x ]  Set-up Backend and Database
- [  ]  Complete Question Template page layout
- [  ]  Question template page functionality for all questions

**Comment by DrakeHunterK7** [comment]
Acceptance testing for this user story:

If the following steps are completed in order and result in success, this story should be completed and should therefore be marked as closed:

1) Log in
2) Go to the All Question page
3) Click on any of the questions in the All Questions page. It should take you to that question's individual page. 
4) Scroll to the bottom of the question's individual page. You will see a Post Answer text area. 
5) Enter your answer in the text area
6) Click on "Submit"
7) The page will now refresh. If you see your answer posted on the page now, this feature now works and therefore this story is complete.

**Comment by DrakeHunterK7** [comment]
Acceptance testing criteria for this user story have been met. The user can now post answers to questions. Therefore this story is now marked closed and completed.
