### ISSUE TITLE
Improvement of backend ListAnswer function

### ISSUE THREAD

**Issue by ChenChenYellow** [DrakeHunterK7/SOEN-341-Fall-2021-Team-9-Stack-Bubbling-#109]
![image](https://user-images.githubusercontent.com/39663046/140572416-b1726a87-d94e-4f91-bff4-c68b1a1b7ede.png)
![image](https://user-images.githubusercontent.com/39663046/140572448-73967540-a0ad-4353-94c9-1acb8d91e56b.png)
Improvement of backend ListAnswer function
ListAnswer should return User_ID and Username as well as all the information in an Answer
User the QuestionList as reference

**Comment by AutoSleep** [comment]
@ChenChenYellow Can you link the specific PR to this tasks thank you
