### ISSUE TITLE
As a normal user,  I want to be able to mark an answer as "accepted" so that I can tell others that this answer is the most helpful for me and it solved my problem.

### ISSUE THREAD

**Issue by ChenChenYellow** [DrakeHunterK7/SOEN-341-Fall-2021-Team-9-Stack-Bubbling-#11]
As an owner of a question, I want to be able to mark an answer as "accepted", so that I can tell others that this answer is the most helpful for me and it solved my problem.
Related epic story #21

**Comment by DrakeHunterK7** [comment]
Acceptance testing for this user story:

If the following steps are executed in the following order and result in success, then this story will therefore be closed.

1) Log in and go to the All Questions page
2) Find one of your questions that already has one or more answers, and go that question's page. 
3) On any of the answers, press the "Declare Best Answer" button. The page should automatically reload at this point. 
4) The best answer should now be visible with separate styling. If this step is successful, then this feature is therefore complete and this user story should be marked as closed and complete.

**Comment by DrakeHunterK7** [comment]
This feature is complete as of Sprint 4
