### ISSUE TITLE
As an owner of a question and answer, I would like to receive notification when someone downvote or upvote my question. User Story of Epic Story #118 

### ISSUE THREAD

**Issue by AutoSleep** [DrakeHunterK7/SOEN-341-Fall-2021-Team-9-Stack-Bubbling-#115]
This is the additional feature that we have to add to this system according to the meeting

**Comment by AutoSleep** [comment]
Thank you for your suggestion, I will add it to the acceptance test case

**Comment by DrakeHunterK7** [comment]
This user story is complete as of Sprint 4 and specifically the #127 pull request and the #124 pull request
