### ISSUE TITLE
As a normal user, I want to be able to see my past activities on the website so I can check them out and keep track of my activities

### ISSUE THREAD

**Issue by ChenChenYellow** [DrakeHunterK7/SOEN-341-Fall-2021-Team-9-Stack-Bubbling-#12]
As an User of the website, I want to be able to see my past activities on the website, ie. my questions, my answers, my comments and my voting, so that I can quickly go to the topic.

**Comment by DrakeHunterK7** [comment]
Acceptance testing for this user story:

If the following steps are executed in the following order and result in success, then this story will therefore be closed.

1) Log in and go to User Profile
2) In the Past Activities section, click on of the activities. 
3) If you are successfully redirected to the location of the activity then this feature is complete and should be marked closed and complete.

**Comment by DrakeHunterK7** [comment]
This feature is not important as per project requirements. Hence it is now marked closed.
