### ISSUE TITLE
As a normal user, I want to be able to log out so that other users of my computer won't be able to use my account without my permission.

### ISSUE THREAD

**Issue by ChenChenYellow** [DrakeHunterK7/SOEN-341-Fall-2021-Team-9-Stack-Bubbling-#13]
As an User of the website, I want to be able to log out, so that other user of my computer won't be able to use my account without my permission.

**Comment by DrakeHunterK7** [comment]
Acceptance testing for this user story:

If the following steps are executed in the following order and result in success, then this story will therefore be closed. 

1) Log in using your email and password
2) Then log out
3) Try to post a question or answer after logging out. 
4) If you can't post a question or answer, you have successfully logged out and your access token is now no longer active.

**Comment by DrakeHunterK7** [comment]
Since the log out feature works and satisfies the testing criteria as seen above, this story is therefore closed and complete.
