### ISSUE TITLE
As a user, I want to be able to decide the best answer to the question so that people know what answer was most helpful.

### ISSUE THREAD

**Issue by vrajp434** [DrakeHunterK7/SOEN-341-Fall-2021-Team-9-Stack-Bubbling-#21]

**Comment by massdarkness11** [comment]
As the user asking a question, I want to be able to chose a best answer to give feedback that will help users with similar problems.

**Comment by massdarkness11** [comment]
As a random user asking the same question, I want to be able to quickly find and identify the best answer.

**Comment by massdarkness11** [comment]
Conversation
As a user providing answers, I want to be able to see if the OP has already found a good answer to their question.

**Comment by massdarkness11** [comment]
Confirmation
OP chooses an answer to the question. The answer chosen is clearly marked and highlighted for all users of the website. 
Verify that the OP can change the chosen answer. 
Verify that only the OP can choose an answer. 
Verify that every user can see the chosen answer.

**Comment by DrakeHunterK7** [comment]
This feature is complete as of Sprint 4.
