### ISSUE TITLE
As a normal user, I want be able to register for a personal account so that I can keep track of my activities.

### ISSUE THREAD

**Issue by ChenChenYellow** [DrakeHunterK7/SOEN-341-Fall-2021-Team-9-Stack-Bubbling-#3]
As a User of the website, I want be able to register for a personnel account, so that I can keep track of my activities.

**Comment by DrakeHunterK7** [comment]
Acceptance testing for this user story:

If the following steps are executed in the following order and result in success, then this story will therefore be closed.

1) Go to Register page
2) Enter in all the fields (Email, Username, Password, Confirm Password)
3) Click on "Register". If you entered everything right, you should be redirected to the Login page.
4) Now log in using the email and password you just registered with. 
5) Once you log in, you should be able to see a welcome message with your username at the top right. If you see this, it means you have successfully registered and this feature is complete. Therefore this user story should be closed and completed.
