### ISSUE TITLE
As a normal user, I want to be able to change the password of my account in case I would like to have a better password

### ISSUE THREAD

**Issue by ChenChenYellow** [DrakeHunterK7/SOEN-341-Fall-2021-Team-9-Stack-Bubbling-#4]
As an User of the website, I want to able to change the password of my account, so that I can manage all my password easier.

**Comment by DrakeHunterK7** [comment]
Acceptance testing for this user story:

If the following steps are executed in the following order and result in success, then this story will therefore be closed.

1) Register a new Account and Log in with that account.
2) Go to User Profile and under Profile, click on "Change Password"
3) Change the password as described on screen. 
4) Log out and Log in again using the old password. This should fail.
5) Now try logging in using the new password. If you are able to log in successfully with the new password, this feature is therefore complete and this user story should be closed.

**Comment by DrakeHunterK7** [comment]
Since this feature is not required for the project, and since we don't have much time for this feature, it will have to be marked closed.
