### ISSUE TITLE
As a normal user, I want to be able to login with my account so that all my activities will be tracked.

### ISSUE THREAD

**Issue by ChenChenYellow** [DrakeHunterK7/SOEN-341-Fall-2021-Team-9-Stack-Bubbling-#5]
As an User of the website, I want to be able to login with my account, so that all my activities will be tracked.

**Comment by DrakeHunterK7** [comment]
Acceptance testing for this user story:

If the following steps are executed in the following order and result in success, then this story will therefore be closed.

1) Go to the Login page and enter in your valid email and password.
2) The header should change and you should see a welcome message referencing your username at the top right. 
3) Go to Post Question and post a new question. 
4) Go to All Questions and confirm if your new question is at the top of the list. If you see your question, it means you have successfully logged in. Therefore, this feature is complete and this user story is closed.

**Comment by DrakeHunterK7** [comment]
This story has passed the acceptance test as described above. Therefore it is now closed.
