### ISSUE TITLE
As a normal user, I want to be able to view people's post so that I can look for a solution to my problems.

### ISSUE THREAD

**Issue by ChenChenYellow** [DrakeHunterK7/SOEN-341-Fall-2021-Team-9-Stack-Bubbling-#6]
As an User of the website, I want to be able to view people's post, so that I can look for the solution of my problems.

**Comment by ChenChenYellow** [comment]
Even not logged on, an user should still be able to see posts.

**Comment by DrakeHunterK7** [comment]
This feature passed the acceptance test as described above. Hence, this story is now complete and closed.
