### ISSUE TITLE
As a normal user, I want to be able to comment under a post so that I can ask others for more detail of the same topic.

### ISSUE THREAD

**Issue by ChenChenYellow** [DrakeHunterK7/SOEN-341-Fall-2021-Team-9-Stack-Bubbling-#7]
As an User of the website, I want to able to comment under a post, so that I can ask others for more detail of the same topic.

**Comment by DrakeHunterK7** [comment]
Acceptance testing for this user story:

If the following steps are executed in the following order and result in success, then this story will therefore be closed.

1) Log in and go to the All Questions page
2) Click on any question
3) Comment under the question. The page should refresh automatically. 
4) If your comment if now visible on the page as part of the question , this this feature is therefore complete, and this story should be marked closed and complete.

**Comment by DrakeHunterK7** [comment]
This feature is not required as per project requirements and nor do we have the time to implement this, unfortunately. Hence this story is closed.
